//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyScheduler
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9B8D99_PartySchedulerEntities : DbContext
    {
        public DB_9B8D99_PartySchedulerEntities()
            : base("name=DB_9B8D99_PartySchedulerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Party1> Party1 { get; set; }
        public DbSet<Party2> Party2 { get; set; }
        public DbSet<Party3> Party3 { get; set; }
    }
}
